yatube/about/urls.py
from django.urls import path

from . import views

app_name = 'about'

urlpatterns = [
    path(
        'author/',
        views.AboutAuthorView.as_view(),
        name='author'
    ),
    path(
        'tech/',
        views.AboutTechView.as_view(),
        name='tech'
    ),
]

yatube/posts/urls.py
from django.urls import path

from . import views

app_name = 'posts'

urlpatterns = [
    path('', views.index, name='index'),
    path('group/<slug:slug>/', views.group_list, name='group_list'),
    path('profile/<str:username>/', views.profile, name='profile'),
    path('posts/<int:post_id>/', views.post_detail, name='post_detail'),
    path('create/', views.post_create, name='post_create'),
    path('posts/<int:post_id>/edit/', views.post_edit, name='post_edit'),
    path(
        'posts/<int:post_id>/comment/',
        views.add_comment,
        name='add_comment'
    ),
    path('follow/', views.follow_index, name='follow_index'),
    path(
        'profile/<str:username>/follow/',
        views.profile_follow,
        name='profile_follow'
    ),
    path(
        'profile/<str:username>/unfollow/',
        views.profile_unfollow,
        name='profile_unfollow'
    ),
]

yatube/yatube/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import include, path

urlpatterns = [
    path('', include('posts.urls', namespace='posts')),
    path('admin/', admin.site.urls),
    path('auth/', include('users.urls', namespace='users')),
    path('auth/', include('django.contrib.auth.urls')),
    path('about/', include('about.urls', namespace='about')),
]

handler404 = 'core.views.page_not_found'
handler403 = 'core.views.permission_denied'
handler500 = 'core.views.server_error'

if settings.DEBUG:
    import debug_toolbar
    urlpatterns = [
        path('__debug__/', include(debug_toolbar.urls)),
    ] + urlpatterns

if settings.DEBUG:
    urlpatterns += static(
        settings.MEDIA_URL, document_root=settings.MEDIA_ROOT
    )

yatube/posts/models.py
from django.contrib.auth import get_user_model
from django.db import models

User = get_user_model()


class Group(models.Model):
    title = models.CharField(
        verbose_name='Заголовок',
        max_length=200,
        help_text='Краткое наименование группы'
    )
    slug = models.SlugField(
        verbose_name='slug группы',
        help_text='Идентификатор группы для адресной строки',
        unique=True
    )
    description = models.TextField(
        verbose_name='Описание',
        help_text='Развёрнутое описание группы'
    )

    def __str__(self):
        return self.title


class Post(models.Model):
    text = models.TextField(
        verbose_name='Текст поста',
        help_text='Изложите свои мысли'
    )
    pub_date = models.DateTimeField(
        auto_now_add=True,
        verbose_name='Дата публикации',
        help_text='Дата заполняется автоматически'
    )
    author = models.ForeignKey(
        User,
        on_delete=models.CASCADE,
        related_name='posts',
        verbose_name='Автор поста',
        help_text='Автор заполняется автоматически'
    )
    group = models.ForeignKey(
        Group,
        on_delete=models.SET_NULL,
        related_name='posts',
        blank=True,
        null=True,
        verbose_name='Группа поста',
        help_text='Выберите группу по содержанию поста'
    )
    image = models.ImageField(
        upload_to='posts/',
        blank=True,
        verbose_name='картинка поста',
        help_text='Загрузите картинку'
    )

    class Meta:
        ordering = ('-pub_date',)
        verbose_name = 'Пост'
        verbose_name_plural = 'Посты'

    def __str__(self):
        return self.text[:15]


class Comment(models.Model):
    post = models.ForeignKey(
        Post,
        on_delete=models.CASCADE,
        related_name='comments',
        verbose_name='Пост для комментирования',
        help_text='Пост заполняется автоматически'
    )
    author = models.ForeignKey(
        User,
        on_delete=models.CASCADE,
        related_name='comments',
        verbose_name='Автор комментария',
        help_text='Автор заполняется автоматически'
    )
    text = models.TextField(
        verbose_name='Текст комментария',
        help_text='Напишите здесь свой комментарий'
    )
    created = models.DateTimeField(
        auto_now_add=True,
        verbose_name='Дата комментария',
        help_text='Дата заполняется автоматически'
    )


class Follow(models.Model):
    user = models.ForeignKey(
        User,
        on_delete=models.CASCADE,
        related_name='follower',
        verbose_name='Подписчик',
        help_text='Пользователь, который подписывается'
    )
    author = models.ForeignKey(
        User,
        on_delete=models.CASCADE,
        related_name='following',
        verbose_name='Автор подписки',
        help_text='Пользователь, на которого подписываются'
    )

yatube/posts/forms.py
from django.forms.models import ModelForm

from .models import Comment, Post


class PostForm(ModelForm):
    class Meta:
        model = Post
        fields = ('text', 'group', 'image',)


class CommentForm(ModelForm):
    class Meta:
        model = Comment
        fields = ('text',)

yatube/posts/views.py
from django.contrib.auth.decorators import login_required
from django.core.paginator import Paginator
from django.shortcuts import get_object_or_404, redirect, render
from django.views.decorators.cache import cache_page

from .forms import CommentForm, PostForm
from .models import Follow, Group, Post, User

LIST_VOLUME: int = 10
CACHE_DELAY_SECONDS: float = 20


@cache_page(CACHE_DELAY_SECONDS)
def index(request):
    template = 'posts/index.html'
    post_list = Post.objects.order_by('-pub_date')
    paginator = Paginator(post_list, LIST_VOLUME)
    page_number = request.GET.get('page')
    page_obj = paginator.get_page(page_number)
    context = {'page_obj': page_obj}
    return render(request, template, context)


def group_list(request, slug):
    group = get_object_or_404(Group, slug=slug)
    post_list = group.posts.order_by('-pub_date')
    paginator = Paginator(post_list, LIST_VOLUME)
    page_number = request.GET.get('page')
    page_obj = paginator.get_page(page_number)
    template = 'posts/group_list.html'
    context = {
        'group': group,
        'page_obj': page_obj,
    }
    return render(request, template, context)


def profile(request, username):
    selected_user = get_object_or_404(User, username=username)
    post_list = selected_user.posts.order_by('-pub_date')
    count = selected_user.posts.count
    paginator = Paginator(post_list, LIST_VOLUME)
    page_number = request.GET.get('page')
    page_obj = paginator.get_page(page_number)
    template = 'posts/profile.html'
    following = request.user.is_authenticated and Follow.objects.filter(
        user=request.user,
        author=selected_user
    ).exists()
    context = {
        'author': selected_user,
        'count': count,
        'page_obj': page_obj,
        'following': following,
    }
    return render(request, template, context)


def post_detail(request, post_id):
    selected_post = get_object_or_404(Post, pk=post_id)
    count = selected_post.author.posts.count
    comments = selected_post.comments.all()
    context = {
        'selected_post': selected_post,
        'count': count,
        'form': CommentForm(),
        'comments': comments,
    }
    return render(request, 'posts/post_detail.html', context)


@login_required
def post_create(request):
    form = PostForm(request.POST or None, files=request.FILES or None)
    if form.is_valid():
        post = form.save(commit=False)
        post.author = request.user
        post.save()
        return redirect('posts:profile', request.user.username)
    context = {'form': form, 'is_edit': False}
    return render(request, 'posts/create_post.html', context)


def post_edit(request, post_id):
    selected_post = get_object_or_404(Post, pk=post_id)
    if selected_post.author != request.user:
        return redirect('posts:post_detail', post_id)
    form = PostForm(
        request.POST or None,
        files=request.FILES or None,
        instance=selected_post
    )
    if form.is_valid():
        form.save()
        return redirect('posts:post_detail', post_id)
    context = {'form': form, 'is_edit': True, 'post_id': post_id}
    return render(request, 'posts/create_post.html', context)


@login_required
def add_comment(request, post_id):
    post = get_object_or_404(Post, pk=post_id)
    form = CommentForm(request.POST or None)
    if form.is_valid():
        comment = form.save(commit=False)
        comment.author = request.user
        comment.post = post
        comment.save()
    return redirect('posts:post_detail', post_id=post_id)


@login_required
def follow_index(request):
    post_list = Post.objects.filter(
        author__following__user=request.user
    ).order_by('-pub_date')
    paginator = Paginator(post_list, LIST_VOLUME)
    page_number = request.GET.get('page')
    page_obj = paginator.get_page(page_number)
    context = {'page_obj': page_obj}
    return render(request, 'posts/follow.html', context)


@login_required
def profile_follow(request, username):
    author = get_object_or_404(User, username=username)
    if (author != request.user) and (not Follow.objects.filter(
        user=request.user,
        author__exact=author
    ).exists()):
        Follow.objects.create(user=request.user, author=author)
    return redirect('posts:profile', username)


@login_required
def profile_unfollow(request, username):
    author = get_object_or_404(User, username=username)
    if Follow.objects.filter(user=request.user, author=author).exists():
        Follow.objects.filter(user=request.user, author=author).delete()
    return redirect('posts:profile', username)

yatube/templates/posts/create_post.html
{% extends "base.html" %}
{% block title %}
  {% if is_edit %}
    Редактировать пост
  {% else %}
    Новый пост
  {% endif %}
{% endblock %}
{% block content %}
  {% load user_filters %} 
        <div class="row justify-content-center">
          <div class="col-md-8 p-5">
            <div class="card">
              <div class="card-header">       
                {% if is_edit %}
                  Редактировать пост
                {% else %}
                  Новый пост
                {% endif %}             
              </div>
              <div class="card-body">
                {% if form.errors %}
                {% for field in form %}
                  {% for error in field.errors %}            
                    <div class="alert alert-danger">
                      {{ error|escape }}
                    </div>
                  {% endfor %}
                {% endfor %}
                {% for error in form.non_field_errors %}
                  <div class="alert alert-danger">
                    {{ error|escape }}
                  </div>
                {% endfor %}
              {% endif %}
              <form method="post" enctype="multipart/form-data" action="
                {% if is_edit %}
                  {% url 'posts:post_edit' post_id %}
                {% else %}
                  {% url 'posts:post_create' %}
                {% endif %}     
              ">
                {% csrf_token %}
                {% for field in form %}
                  <div class="form-group row my-3"
                    {% if field.field.required %} 
                      aria-required="true"
                    {% else %}
                      aria-required="false"
                    {% endif %}
                  >
                    <label for="{{ field.id_for_label }}">
                      {{ field.label }}
                      {% if field.field.required %}
                        <span class="required text-danger">*</span>
                      {% endif %}
                    </label>
                  <div>
                  {{ field|addclass:'form-control' }}
                  {% if field.help_text %}
                    <small id="{{ field.id_for_label }}-help" class="form-text text-muted">
                      {{ field.help_text|safe }}
                    </small>
                  {% endif %}
                {% endfor %}
                  <div class="d-flex justify-content-end">
                    <button type="submit" class="btn btn-primary">
                      {% if is_edit %}
                        Сохранить
                      {% else %}
                        Добавить
                      {% endif %}
                    </button>
                  </div>
                </form>
              </div>
            </div>
          </div>
        </div>
{% endblock %}

yatube/templates/posts/follow.html
{% extends 'base.html' %}
{% load thumbnail %}
{% block title %}
  Избранные авторы
{% endblock %} 
{% block content %}
  {% include 'posts/includes/switcher.html' %}
  <h1>Избранные авторы</h1>
  <article>
    {% for post in page_obj %}
      <ul>
        <li>
          Автор: {{ post.author.get_full_name }}
          <a href="{% url 'posts:profile' post.author.username %}">все посты пользователя </a>
        </li>
        <li>
          Дата публикации: {{ post.pub_date|date:"d E Y" }}
        </li>
      </ul>
      {% thumbnail post.image "960x339" crop="center" upscale=True as im %}
        <img class="card-img my-2" src="{{ im.url }}">
      {% endthumbnail %}
      <p>{{ post.text }}</p>
      <a href="{% url 'posts:post_detail' post.pk %}">подробная информация </a>
      <br>
      {% if post.group %}   
        <a href="{% url 'posts:group_list' post.group.slug %}">все записи группы</a>
      {% endif %}
      {% if not forloop.last %}<hr>{% endif %}
    {% endfor %}
    {% include 'posts/includes/paginator.html' %}
  </article>  
{% endblock %}

yatube/templates/posts/group_list.html
{% extends 'base.html' %}
{% load thumbnail %}
{% block title %}
  {{ group.title }}
{% endblock %} 
{% block content %}
  <h1> {{ group.title }} </h1>
  <p>
    {{ group.description }}
  </p>
  <article>
    {% for post in page_obj %}
      <ul>
        <li>
          Автор: {{ post.author.get_full_name }}
          <a href="{% url 'posts:profile' post.author.username %}">все посты пользователя </a>
        </li>
        <li>
          Дата публикации: {{ post.pub_date|date:"d E Y" }}
        </li>
      </ul>
      {% thumbnail post.image "960x339" crop="center" upscale=True as im %}
        <img class="card-img my-2" src="{{ im.url }}">
      {% endthumbnail %}
      <p>{{ post.text }}</p>
      <a href="{% url 'posts:post_detail' post.pk %}">подробная информация </a>
      <br>
      {% if post.group %}   
        <a href="{% url 'posts:group_list' post.group.slug %}">все записи группы</a>
      {% endif %}
      {% if not forloop.last %}<hr>{% endif %}
    {% endfor %}
    {% include 'posts/includes/paginator.html' %}
  </article> 
{% endblock %}

yatube/templates/posts/index.html
{% extends 'base.html' %}
{% load thumbnail %}
{% block title %}
  Последние обновления на сайте
{% endblock %} 
{% block content %}
  {% include 'posts/includes/switcher.html' %}
  <h1>Последние обновления на сайте</h1>
  <article>
    {% for post in page_obj %}
      <ul>
        <li>
          Автор: {{ post.author.get_full_name }}
          <a href="{% url 'posts:profile' post.author.username %}">все посты пользователя </a>
        </li>
        <li>
          Дата публикации: {{ post.pub_date|date:"d E Y" }}
        </li>
      </ul>
      {% thumbnail post.image "960x339" crop="center" upscale=True as im %}
        <img class="card-img my-2" src="{{ im.url }}">
      {% endthumbnail %}
      <p>{{ post.text }}</p>
      <a href="{% url 'posts:post_detail' post.pk %}">подробная информация </a>
      <br>
      {% if post.group %}   
        <a href="{% url 'posts:group_list' post.group.slug %}">все записи группы</a>
      {% endif %}
      {% if not forloop.last %}<hr>{% endif %}
    {% endfor %}
    {% include 'posts/includes/paginator.html' %}
  </article>  
{% endblock %}

yatube/templates/posts/post_detail.html
{% extends 'base.html' %}
{% load thumbnail %}
{% block title %}
  {% load user_filters %}
  {{ selected_post.text|limit_str:30 }}
{% endblock %} 
{% block content %}
  <div class="row">
    <aside class="col-12 col-md-3">
      <ul class="list-group list-group-flush">
        <li class="list-group-item">
          Дата публикации: {{ selected_post.pub_date|date:"d E Y" }} 
        </li>
        {% if selected_post.group %}  
          <li class="list-group-item">
            Группа: {{ selected_post.group }}
            <a href="{% url 'posts:group_list' selected_post.group.slug %}">все записи группы</a>
          </li>
        {% endif %}
        <li class="list-group-item">
          Автор: {{ selected_post.author.first_name }} {{ selected_post.author.last_name }}
        </li>
        <li class="list-group-item d-flex justify-content-between align-items-center">
          Всего постов автора:  <span > {{  count  }} </span>
        </li>
        <li class="list-group-item">
          <a href="{% url 'posts:profile' selected_post.author.username %}">все посты пользователя</a>
        </li>
      </ul>
    </aside>
    <article class="col-12 col-md-9">
      {% thumbnail selected_post.image "960x339" crop="center" upscale=True as im %}
        <img class="card-img my-2" src="{{ im.url }}">
      {% endthumbnail %}
      <p>
        {{ selected_post.text }}
      </p>
      <a class="btn btn-primary" href="{% url 'posts:post_edit' selected_post.pk %}">
        редактировать запись
      </a>
      {% if user.is_authenticated %}
        <div class="card my-4">
          <h5 class="card-header">Добавить комментарий:</h5>
          <div class="card-body">
            <form method="post" action="{% url 'posts:add_comment' selected_post.id %}">
              {% csrf_token %}      
              <div class="form-group mb-2">
                {{ form.text|addclass:"form-control" }}
              </div>
              <button type="submit" class="btn btn-primary">Отправить</button>
            </form>
          </div>
        </div>
      {% endif %}
      {% for comment in comments %}
        <div class="media mb-4">
          <div class="media-body">
            <h5 class="mt-0">
              <a href="{% url 'posts:profile' comment.author.username %}">
                {{ comment.author.username }}
              </a>
            </h5>
            <p>
              {{ comment.text }}
            </p>
          </div>
        </div>
      {% endfor %}
    </article>
  </div>
{% endblock %} 

yatube/templates/posts/profile.html
{% extends 'base.html' %}
{% load thumbnail %}
{% block title %}
  Профайл пользователя {{ author.first_name }} {{ author.last_name }}
{% endblock %} 
{% block content %}
<div class="mb-5">
  <h1>Все посты пользователя {{ author.first_name }} {{ author.last_name }}</h1>
  <h3>Всего постов: {{  count  }} </h3>
  {% if following %}
  <a
    class="btn btn-lg btn-light"
    href="{% url 'posts:profile_unfollow' author.username %}" role="button"
  >
    Отписаться
  </a>
  {% else %}
    <a
      class="btn btn-lg btn-primary"
      href="{% url 'posts:profile_follow' author.username %}" role="button"
    >
      Подписаться
    </a>
  {% endif %}
  </div>
  {% for post in page_obj %}
    <article>
      <ul>
        <li>
          Дата публикации: {{ post.pub_date|date:"d E Y" }} 
        </li>
      </ul>
      {% thumbnail post.image "960x339" crop="center" upscale=True as im %}
        <img class="card-img my-2" src="{{ im.url }}">
      {% endthumbnail %}
      <p>{{ post.text }}</p>
      <a href="{% url 'posts:post_detail' post.pk %}">подробная информация </a>
    </article>    
    {% if post.group %}   
      <a href="{% url 'posts:group_list' post.group.slug %}">все записи группы</a>
    {% endif %}       
    {% if not forloop.last %}<hr>{% endif %}
  {% endfor %}
  {% include 'posts/includes/paginator.html' %}
{% endblock %} 